### ISSUE TITLE
Project shows an empty window

### ISSUE THREAD

**Issue by ScottPierce** [amaurym/cra-lerna-electron#134]
Thanks for putting this up! Projects like these are really helpful for newbies like me when they are trying to combine complicated technologies like this together. Sadly - it doesn't seem to be working for me or other members on my team. We just see this after running `yarn start`:

<img width="912" alt="Screen Shot 2020-09-21 at 4 39 49 PM" src="https://user-images.githubusercontent.com/871169/93818971-125a7c00-fc29-11ea-88c7-a0ff95c088ec.png">

It'd be great if you could help us get it up and running!

**Comment by amaurymartiny** [comment]
Did you finally figure out?

Does running the 2 run start commands separately work?
```bash
cd packages/crale-electron && yarn start

# in another terminal
cd packages/crale-react && yarn start
```

**Comment by amaury1093** [comment]
Closing as inactive
